name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint and format
        run: pnpm check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck
